### ISSUE TITLE
Noch'n ToDo

### ISSUE THREAD

**Issue by LittleBigPlaye** [fh-erfurt/RateYourStuff#35]
- [ ] Ausgaben aus Code entfernen
- [x] Ausgaben in Testklassen durch Logger Ausgaben ersetzen
- [x] JavaDoc Kommentare schreiben
- [ ] CI implementieren
- [x] Klassen in Packages
- [ ] ToDos auflösen
    - [ ] Comment Löschen Updaten
- [ ] Doku schreiben
    - [x] Klassendiagramm überarbeiten / anpassen / neu
    - [x] Business Sicht (Sequenzdiagramme) (Montag Fragen)
- [x] Resolution Klasse ersetzen

- [x] Untergliederung Packages
    - [x] UserManagement
    - [x] MediaManagement
       - [x] Media Types
           - [x] Books
               - [x] ISBN
           - [x] Series
           - [x] Movie
           - [x] Game     
       - [x] Person
    - [x] ProgressManagement
        - [x] ProgressTypes 
    - [x] CommentManagement
    - [x] RatingManagement  
    - [x] Bcrypt in pom.xml schreiben

**Comment by MKnop2** [comment]
neue UML auf lucidchart
![image](https://user-images.githubusercontent.com/56631092/105635906-e0bb2100-5e65-11eb-9513-2c2d4390ea70.png)
